dbdata:
  image: postgres:9.3
  volumes:
    - /var/lib/postgresql
  command: true
db:
  image: postgres:9.3
  volumes_from:
    - dbdata
  ports:
    - 5432:5432
web:
  build: .
  command: python app/app.py
  volumes:
    - .:/usr/src/app
  ports:
    - 5000:5000
  links:
    - db
  environment:
    - INSTANCE_TYPE=web
    - DB_USER=postgres
    - DB_NAME=postgres
    - DB_PORT=5432
    - DB_HOST=db
